/* Copyright (C) 2008-2020 Allegro DVT2.  All rights reserved. */
// This file was generated by configure. DO NOT MODIFY


#ifndef NUM_COMMAND_REGISTER
#define NUM_COMMAND_REGISTER 128
#endif
#ifndef DECODER_CORE_FREQUENCY
#define DECODER_CORE_FREQUENCY (500 * 1000 * 1000)
#endif
#ifndef DECODER_CORE_FREQUENCY_MARGIN
#define DECODER_CORE_FREQUENCY_MARGIN 10
#endif
#ifndef DECODER_CYCLES_FOR_BLK_32X32
#define DECODER_CYCLES_FOR_BLK_32X32 816
#endif
#ifndef AL_DEC_NUM_CORES
#define AL_DEC_NUM_CORES 2
#endif
#ifndef AL_DEC_NUM_PARSER_PER_CORE
#define AL_DEC_NUM_PARSER_PER_CORE 2
#endif
#ifndef AL_DEC_NUM_CORE_JPEG
#define AL_DEC_NUM_CORE_JPEG 2
#endif
#ifndef HW_IP_BURST_ALIGNMENT
#define HW_IP_BURST_ALIGNMENT 32
#endif
#ifndef AL_DEC_CORE_MAX_WIDTH
#define AL_DEC_CORE_MAX_WIDTH 2048
#endif
#ifndef AL_MAX_ENC_SLICE
#define AL_MAX_ENC_SLICE 200
#endif
#ifndef AL_LOG_LEVEL
#define AL_LOG_LEVEL 0
#endif
#ifndef MAX_NUM_LAYER
#define MAX_NUM_LAYER 1
#endif


#define AL_CONFIGURE_COMMANDLINE "./configure --config-blob customers/Jinxvm/config.ini"
#define AL_VERSION_MAJOR 0
#define AL_VERSION_MINOR 31
#define AL_VERSION_STEP 0

